# Generated by Django 2.2.7 on 2019-11-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegulatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortDesc', models.CharField(max_length=60)),
                ('longDesc', models.TextField()),
                ('ruleReference', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Normativa',
                'verbose_name_plural': 'Normative',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTrainingChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortDesc', models.CharField(max_length=60)),
                ('longDesc', models.TextField()),
                ('enabled', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Metodo di erogazione',
                'verbose_name_plural': 'Metodi di erogazione',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortDesc', models.CharField(max_length=60)),
                ('longDesc', models.TextField()),
                ('enabled', models.BooleanField()),
                ('regulatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventType', to='appEventi.EventRegulatory')),
                ('trainingChannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventTrainingChannel', to='appEventi.EventTrainingChannel')),
            ],
            options={
                'verbose_name': 'Tipologia Evento',
                'verbose_name_plural': 'Tipologie Eventi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortDesc', models.CharField(max_length=60)),
                ('longDesc', models.TextField()),
                ('frontend_visible', models.BooleanField()),
                ('backend_visible', models.BooleanField()),
                ('enabled', models.BooleanField()),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='appEventi.EventType')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'ordering': ['name'],
            },
        ),
    ]
