"""
Django settings for GenericProject project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
#from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0=%+z+a1^h!ioc86n6q!ifkhx!&w0d@&8__m3qv)y2x(&dmron'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Frontend Apps
    'core',
    'appModuli',
    'appForum',
    'appLibri',
    'appEventi',
    'appNews',
    'appContatti',
    'appAccessi',


    # Django Core Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Third Party Apps
    'crispy_forms', # pip install --upgrade pip
    'clear_cache'
]

# impostazione necessaria per django-crispy-forms
CRISPY_TEMPLATE_PACK = "bootstrap4"
#MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
# MESSAGE_TAGS = {
#     messages.DEBUG: 'alert-info',
#     messages.INFO: 'alert-info',
#     messages.SUCCESS: 'alert-success',
#     messages.WARNING: 'alert-warning',
#     messages.ERROR: 'alert-danger',
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GenericProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'core/templates'),
                 os.path.join(BASE_DIR, 'appModuli/templates'),
                 os.path.join(BASE_DIR, 'appAccessi/templates'),
                 os.path.join(BASE_DIR, 'appLibri/templates'),
                 os.path.join(BASE_DIR, 'appAccessi/templates'),
                 os.path.join(BASE_DIR, 'appForum/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GenericProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'it'

DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M']  # '10/25/2006 14:30'
DATE_INPUT_FORMATS = ['%d-%m-%Y']             # '10 ott. 2006'
DATE_FORMATS = ['%d-%m-%Y']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False #messo a false perchè ha la precedenza sul date_format

USE_TZ = True

#URL di default a cui si viene rimandati dopo una corretta login
LOGIN_REDIRECT_URL = "/"

#Da usare solo in fase di sviluppo per emulare le mail inviate a console
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'authsmtp.securemail.pro'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'info@madlyuk.it'
EMAIL_HOST_PASSWORD = 'madlyuk@7777M107064'
DEFAULT_FROM_EMAIL = 'info@g@madlyuk.it'
DEFAULT_TO_EMAIL = 'info@madlyuk.it'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'core/static'),
    os.path.join(BASE_DIR, 'appForum/static'),
    os.path.join(BASE_DIR, 'appEventi/static')
]

STATIC_URL = '/static/'
#STATIC_ROOT = "/home/django/static-serve"


#la cartella con i media file (img, ecc.) è consigliabile tenerla fuori dalla
#cartella di progetto nella stessa posizione dove compare il file manage.py..
#il corso pero' prevede come best-practices di tenerla fuori dal progetto a livello della cartella v_env
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media-serve')
# MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media-serve')
MEDIA_URL = '/media/'
