# Generated by Django 2.2.7 on 2020-02-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discussione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioni', to='appForum.Discussione'),
        ),
    ]
