# Generated by Django 2.2.7 on 2020-02-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appForum', '0002_auto_20200206_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussione',
            name='sezione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioni_sezione', to='appForum.Sezione'),
        ),
    ]
