# Generated by Django 2.2.7 on 2019-12-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('oggetto', models.CharField(max_length=100)),
                ('contenuto', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contatti',
            },
        ),
    ]
