# Generated by Django 2.2.7 on 2019-12-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContatti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatti',
            name='oggetto_due',
            field=models.EmailField(default='0000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='contatti',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
