# Generated by Django 2.2.7 on 2019-12-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContatti', '0002_auto_20191216_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatti',
            name='oggetto_due',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
