# Generated by Django 2.2.7 on 2019-12-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appContatti', '0003_auto_20191216_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatti',
            name='oggetto_due',
        ),
    ]
