# Generated by Django 2.2.7 on 2019-12-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appModuli', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appModule',
            new_name='appModuli',
        ),
    ]
