# Generated by Django 2.2.7 on 2019-12-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModuli', '0002_auto_20191202_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmoduli',
            name='appUrl',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
