# Generated by Django 2.2.7 on 2019-12-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appModuli', '0003_appmoduli_appurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmoduli',
            options={'verbose_name': 'AppModuli', 'verbose_name_plural': 'AppModuli'},
        ),
    ]
