# Generated by Django 2.2.7 on 2020-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModuli', '0005_auto_20200124_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmoduli',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appmoduli',
            name='mainAppView',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='main View'),
        ),
    ]
